#!/bin/sh


# Use neovim for vim if present.
[ -x "$(command -v nvim)" ] && alias vim="nvim" vimdiff="nvim -d"

# /comfy/
alias \
v="vim ." \
x="exit" \
ka="killall" \
bb="byobu" \

# Shortcuts
alias \
cf="~/.config && v" \
cfv="~/.config/nvim && v" \
cfa="~/.config/awesome && v" \
cfs="~/.config/shell && v" \
cfl="~/.config/lf && v" \
cfx="~/.config/x11 && v" \
cfz="~/.config/zsh && v" \
cfk="~/.config/kitty && v" \
cfp="nvim ~/.config/picom.conf" \

# Add verbosity
alias \
cp="cp -iv" \
mv="mv -iv" \
rm="rm -vI" \
mkd="mkdir -pv" \

# Add color
alias \
ls="ls -hN --color=auto --group-directories-first" \
grep="grep --color=auto" \
diff="diff --color=auto" \
ccat="highlight --out-format=ansi" \

# Laziness
alias \
hosts="sudo nvim /etc/hosts" \
push="rsync -avzP --copy-links " \
sup="push ~/projects/http deez:" \

# Forget why
wget="wget --hsts-file='XDG_CACHE_HOME/wget-hsts'" \
