#!/bin/bash

cd

if test -d yay; then
    rm -rf yay
fi

git clone https://aur.archlinux.org/yay.git &&
    cd yay &&
    makepkg -si --noconfirm &&
    cd &&
    rm -rf yay

# Base/Shell
yay -S --needed --noconfirm \
\
`# Standard`\
rsync \
sl \
btop \
neovim \
byobu \
zsh \
lf \
nnn \
\
`# Aur`\
stpv-git \
nvim-packer-git \
oh-my-zsh-git &&

sudo chsh -s /bin/zsh $USER
