#!/bin/bash

cd

if test -d yay; then
    rm -rf yay
fi

if ! type "yay" &> /dev/null; then
    git clone https://aur.archlinux.org/yay.git &&
        cd yay &&
        makepkg -si --noconfirm &&
        cd &&
        rm -rf yay
fi

# Base/Shell
yay -S --needed --noconfirm \
\
`# Standard`\
rsync \
sl \
btop \
neovim \
byobu \
zsh \
lf \
nnn \
kitty-terminfo \
\
`# Aur`\
stpv-git \
nvim-packer-git \
oh-my-zsh-git &&

sudo chsh -s /bin/zsh $USER
