#!/bin/bash

# Base
sudo apt-get -y install \
    btop \
    neovim \
    byobu \
    zsh \
    nnn

# Packer
git clone --depth 1 https://github.com/wbthomason/packer.nvim\
 ~/.local/share/nvim/site/pack/packer/start/packer.nvim

# OhMyZsh
sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" &&
sudo chsh -s /bin/zsh $USER
