#!/bin/bash

# Yay
git clone https://aur.archlinux.org/yay.git &&
cd yay &&
makepkg -si --noconfirm &&
cd &&
rm -rf yay &&

# Base/Shell
yay -S --needed --noconfirm \
\
`# Standard`\
rsync \
btop \
neovim \
byobu \
zsh \
nnn \
\
`# Aur`\
nvim-packer-git \
oh-my-zsh-git &&

rsync -avzP .doors/ ./ &&
sudo chsh -s $(which zsh) $USER
