#!/bin/bash

echo "
=======================================================
Installing D's nux (you're gonna love my nux(really))
=======================================================
"

# Clean up
if test -d Doors; then
    rm -rf Doors
elif test -d .doors; then
    rm -rf .doors
fi

# Prep

cd &&
mkdir .doors

# Bootstrap into distro scripts
. /etc/os-release
OS=$NAME

if [[ $OS == *Arch* ]]; then
    cd &&
        sudo sed '/Color/s/^#//' -i /etc/pacman.conf &&
        sudo pacman -S --needed --noconfirm git rsync base-devel  &&
        git clone https://github.com/adoyle0/Doors.git .doors &&
        .doors/.scripts/doors/install_min_arch

elif [[ $OS == *buntu* ]]; then
    cd &&
        sudo apt-get -y install git rsync &&
        git clone https://github.com/adoyle0/Doors.git .doors &&
        .doors/.scripts/doors/install_min_ubuntu

fi

# Copy it
rsync -avzP .doors/ .
