#!/bin/bash
echo "
=======================================================
 Installing D's nux (you're gonna love my nux(really))
=======================================================
"

. /etc/os-release
OS=$NAME

if [[ $OS == *Arch* ]]; then
    sudo sed '/Color/s/^#//' -i /etc/pacman.conf &&
    sudo pacman -S --needed --noconfirm git rsync base-devel  &&
    git clone https://github.com/adoyle0/Doors.git &&
    rsync -avzP --copy-links Doors/ ./
    .scripts/doors/install_min_arch

elif [[ $OS == *buntu* ]]; then
    .scripts/doors/install_min_ubuntu
fi

echo "
========================
 logout and log back in
========================
plz
";
