#!/bin/sh

set -e

# Copy configs and make a backup if it already exists
printf "\nInstalling Configs..."
for file in configs/*
do
    printf "\n%s..." "$file"
    cp -rbv "$file" "$HOME"/.config/
done

# Copy scripts and make a backup if it already exists
printf "\nInstalling Scripts..."

if [ ! -d "$HOME/.local/bin" ]; then
    mkdir "$HOME/.local/bin"
fi

cp -rbv bin "$HOME"/.local

# Link shell files and make a backup if it already exists
printf "\nLinking shell..."
cp -sbv "$HOME"/.config/shell/profile ~/.zprofile
cp -sbv "$HOME"/.config/x11/xinitrc ~/.xinitrc
