#!/bin/bash

# Full (probably) setup for arch

set -e

# Install yay
cd
if ! type "yay" &> /dev/null; then
    echo "Yay not found, installing..."

    if test -d yay; then
        rm -rf yay
    fi

    git clone https://aur.archlinux.org/yay.git
        cd yay
        makepkg -si --noconfirm
        cd
        rm -rf yay
else
    echo -e  "\nYay is already installed, skipping..."
fi

# Install deps
echo -e "\nInstalling dependencies..."
yay -S --needed --noconfirm \
alacritty \
alsa-utils \
awesome \
beautiful-discord-git \
bluez \
btop \
byobu \
caprine \
chromium \
discord \
fakeroot \
firefox-developer-edition \
gawk \
gimp \
lf \
light \
maim \
mosh \
mpd \
neovim \
nnn \
oh-my-zsh-git \
otf-font-awesome \
playerctl \
powerline-fonts \
python-pywalfox \
pywal-discord-git \
rsync \
sl \
slurp \
spotify-launcher \
steam \
sxiv \
telegram-desktop \
thunderbird \
ttf-font-awesome \
upower \
wal-telegram-git \
xclip \
zsh \

# Set shell
echo ""
sudo chsh -s /bin/zsh $USER
