#!/bin/bash

# Minimal setup for Fedora

set -e

cd

sudo dnf -y install \
sl \
btop \
neovim \
byobu \
zsh \
nnn \
mosh \
clang \

# Packer
if ! test -d ~/.local/share/nvim/site/pack/packer/start/packer.nvim; then
    git clone --depth 1 https://github.com/wbthomason/packer.nvim\
        ~/.local/share/nvim/site/pack/packer/start/packer.nvim
fi

# OhMyZsh
if ! test -d .config/zsh/ohmyzsh; then
    sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
fi

# Set shell
sudo usermod -s /bin/zsh $USER
