#!/bin/bash

cd &&
if ! type "yay" &> /dev/null; then
    echo "Yay not found, installing..." &&

    if test -d yay; then
        rm -rf yay
    fi &&

    git clone https://aur.archlinux.org/yay.git &&
        cd yay &&
        makepkg -si --noconfirm &&
        cd &&
        rm -rf yay
else
    echo -e  "\nYay is already installed, skipping..."
fi &&

echo -e "\nInstalling dependencies..." &&
# Base/Shell
yay -S --needed --noconfirm \
\
`# Standard`\
rsync \
sl \
btop \
neovim \
byobu \
zsh \
lf \
nnn \
alacritty \
river \
waybar \
swaybg \
firefox-developer-edition \
thunderbird \
chromium \
caprine \
fuzzel \
telegram-desktop \
discord \
gimp \
steam \
spotify-launcher \
mako \
pamixer \
playerctl \
gawk \
light \
pywal-discord-git \
beautiful-discord-git \
wal-telegram-git \
python-pywalfox \
oh-my-zsh-git &&

echo "" &&
sudo chsh -s /bin/zsh $USER
