#!/bin/sh

# startx/xinit run this script

# Run xprofile
if [ -f "${XDG_CONFIG_HOME:-$HOME/.config}/x11/xprofile" ]; then
    . "${XDG_CONFIG_HOME:-$HOME/.config}/x11/xprofile"
else
    . "$HOME/.xprofile"
fi

# Set system colors
wal -R

# Optimus
[ -x "$(command -v prime-offload)" ] && prime-offload

# Start awesome
ssh-agent awesome

