#!/bin/sh

# This is called by xinitrc during x startup

# Run multi-monitor config if it exists
if [ -f ".screenlayout/default.sh" ]; then
	. ".screenlayout/default.sh" &
fi

# Tint screen at night    
redshift -l \
    $(curl -s "https://location.services.mozilla.com/v1/geolocate?key=geoclue" \
    | sed 's/.*"lat": \(-\?[0-9.]*\).*"lng": \(-\?[0-9.]*\).*/\1:\2/') &

# Password prompt popup
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &

# Compositor
picom -b &            

# Key repeat rate
xset r rate 200 100 & 

# Hide mouse cursor after inactivity
unclutter &           

# Make clipboard work
xclip &               

