#!/bin/sh

# This is called by xinitrc during x startup

# Run multi-monitor config if it exists
if [ -f ".screenlayout/default.sh" ]; then
	. ".screenlayout/default.sh" &
fi

picom -b &            # Compositor
xset r rate 200 100 & # Key repeat rate
unclutter &           # Hide mouse cursor after inactivity
redshift -l 43:-70 &  # Tint screen at night if you're in new england (this should be changed)    
xclip &               # Make clipboard work
