#!/bin/sh

# startx/xinit run this script

# Tint screen at night
redshift -l \
    "$(curl -s "https://location.services.mozilla.com/v1/geolocate?key=geoclue" \
    | sed 's/.*"lat": \(-\?[0-9.]*\).*"lng": \(-\?[0-9.]*\).*/\1:\2/')" &

# Password prompt popup
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &

# Compositor
picom -b &

# Hide mouse cursor after inactivity
unclutter &

# Make clipboard work
xclip &

# Set up colors

# Run colors script if output dir doesn't exist 
if ! test -d "$HOME"/.cache/wal; then
    [ -x "$(command -v wallust )" ] && "$(bream setbg)"
fi

export XDG_CURRENT_DESKTOP=GNOME
if [ -f "${XDG_CONFIG_HOME:-$HOME/.cache}/wal/colors.Xresources" ]; then
    xrdb -merge -quiet ~/.cache/wal/colors.Xresources
fi

# Optimus
[ -x "$(command -v prime-offload)" ] && prime-offload

# Keyboard lights
[ -x "$(command -v keyledsd)" ] && keyledsd &

# Start awesome
ssh-agent awesome
