#!/bin/sh

# Keyboard lights
[ -x "$(command -v g610-led)" ] && g610-led -a ff

# Colors
[ -x "$(command -v wal)" ] && wal -Rnq

export PATH
PATH="$PATH:$(du "$HOME/.local/bin" | cut -f2 | paste -sd ':' -)"

if test -d "$HOME"/.local/share/cargo/bin; then
    PATH="$PATH:$HOME/.local/share/cargo/bin"
fi

unsetopt PROMPT_SP

# Default programs:
export BROWSER="firefox-developer-edition"
export EDITOR="nvim"
export TERMINAL="alacritty"
export PAGER="bat"

# Move config files out of home and into .config/
export ANDROID_SDK_HOME="${XDG_CONFIG_HOME:-$HOME/.config}/android"
export CARGO_HOME="${XDG_DATA_HOME:-$HOME/.local/share}/cargo"
export GOPATH="${XDG_DATA_HOME:-$HOME/.local/share}/go"
export GTK2_RC_FILES="${XDG_CONFIG_HOME:-$HOME/.config}/gtk-2.0/gtkrc-2.0"
export HISTFILE="${XDG_DATA_HOME:-$HOME/.local/share}/history"
export KODI_DATA="${XDG_DATA_HOME:-$HOME/.local/share}/kodi"
export LESSHISTFILE="-"
export PASSWORD_STORE_DIR="${XDG_DATA_HOME:-$HOME/.local/share}/password-store"
export TMUX_TMPDIR="$XDG_RUNTIME_DIR"
export ZDOTDIR="${XDG_CONFIG_HOME:-$HOME/.config}/shell/zsh"

# Other program settings:
export FZF_DEFAULT_OPTS="--layout=reverse --height 40%"
export QT_QPA_PLATFORMTHEME="gtk2"	# Have QT use gtk2 theme.

# export LESS=-R
# export LESSOPEN="| /usr/bin/highlight -O ansi %s 2>/dev/null"
# export LESS_TERMCAP_mb
# LESS_TERMCAP_mb="$(printf '%b' '[1;31m')"
# export LESS_TERMCAP_md
# LESS_TERMCAP_md="$(printf '%b' '[1;36m')"
# export LESS_TERMCAP_me
# LESS_TERMCAP_me="$(printf '%b' '[0m')"
# export LESS_TERMCAP_se
# LESS_TERMCAP_se="$(printf '%b' '[0m')"
# export LESS_TERMCAP_so
# LESS_TERMCAP_so="$(printf '%b' '[01;44;33m')"
# export LESS_TERMCAP_ue
# LESS_TERMCAP_ue="$(printf '%b' '[0m')"
# export LESS_TERMCAP_us
# LESS_TERMCAP_us="$(printf '%b' '[1;32m')"
#
# Multithreading
export XZ_DEFAULTS="-T 0"
