[general]
import = ["~/.cache/wal/colors-alacritty.toml"]

[font]
normal = { family = "CommitMono Nerd Font Mono", style = "Regular" }
bold = { family = "CommitMono Nerd Font Mono", style = "Bold" }
italic = { family = "CommitMono Nerd Font Mono", style = "Italic" }
bold_italic = { family = "CommitMono Nerd Font Mono", style = "Bold Italic" }
size = 15

[window]
opacity = 0.90

[env]
WINIT_X11_SCALE_FACTOR = "1.0"

[colors]
transparent_background_colors = true
